### ISSUE TITLE
Github Labels 

### ISSUE THREAD

**Issue by coreypotter** [coreypotter/kindling#22]
https://robinpowered.com/blog/best-practice-system-for-organizing-and-tagging-github-issues/

**Comment by delster** [comment]
Added most of these. Left out the platform since we have just 1, and "in progress" and "watchlist" as they're boards.

**Comment by coreypotter** [comment]
Perfect, thanks!

**Comment by delster** [comment]
Going to add platforms: core, extra to represent features intended for the free them and the premium solution, be that theme, plugin, whatever. Thoughts?

**Comment by coreypotter** [comment]
Haha, I was just about to add those, but then thought those projects would likely be in different repos. Either way, good to have the tags here so that if I add a feature that doesn't belong, it can get tagged and transferred.
