### ISSUE TITLE
Move Typography Options In Customizer

### ISSUE THREAD

**Issue by coreypotter** [coreypotter/kindling#24]
@delster I know you'll hate me for this, but I feel like it is best for the usability. 

I want to move the typography options for the header and footer to their respective customizer panes. 

![screenshot_042617_092300_am](https://cloud.githubusercontent.com/assets/12460572/25436655/f30060fa-2a61-11e7-88f8-207b3be1a6fc.jpg)

I'm not 100% sure what the "footer menu" typography settings are for, but we may be able to get rid of that completely. 

Logo typography should go to Header>Logo and be labeled as "Font to use if no logo is uploaded."

Main Menu will go under "main styling"

Main Menu Dropdowns will go under "dropdown styling"

Mobile dropdown under "Styling: mobile sidebar menu"

**Comment by delster** [comment]
Incoming commit with just the "Footer Copyright" section for testing.
