### ISSUE TITLE
Schema Items using # instead of //

### ISSUE THREAD

**Issue by coreypotter** [coreypotter/kindling#34]
https://search.google.com/structured-data/testing-tool/u/0/

**Comment by delster** [comment]
I think I fixed this in an earlier commit but hadn't seen that it had a card.. so maybe this is Done?

**Comment by coreypotter** [comment]
#s are out, but now there is no https

![wordpress-85983-264001_cloudwaysapps_com_ _just_another_wordpress_site](https://cloud.githubusercontent.com/assets/12460572/26031396/5b63e3de-383f-11e7-9889-d998e00c1b78.jpg)
