### ISSUE TITLE
Jumping Logo on Hover

### ISSUE THREAD

**Issue by coreypotter** [coreypotter/kindling#36]
Hover animation causes slight "jumping" on logo.

**Comment by coreypotter** [comment]
NOTE: Doesn't happen on centered header style, only left logo and top menu.

**Comment by delster** [comment]
Can't recreate this.

**Comment by coreypotter** [comment]
-webkit-backface-visibility: hidden;

**Comment by coreypotter** [comment]
@delster still happening on inline header
