### ISSUE TITLE
Adjust Logo Max Width

### ISSUE THREAD

**Issue by coreypotter** [coreypotter/kindling#8]
The mobile menu drops down under logo on mobile when logo is too wide. Currently, the mobile width/height cannot be adjusted separately from the desktop logo. On desktop we use height, but on mobile I think users will be more concerned with width. 

![image](https://cloud.githubusercontent.com/assets/12460572/24878848/c60080aa-1e02-11e7-86fc-e405b4d70266.png)

**Comment by delster** [comment]
Alternate mobile options obsolete this issue, as well as centering the menu on its own line.

**Comment by coreypotter** [comment]
I agree, but this does give a good screenshot for reference when we test it out.
